name: Deploy frontend to Vercel

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Vercel deploy (production)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "VERCEL_TOKEN is not set; skipping deploy";
            exit 0;
          fi
          vercel --prod --confirm
